### ISSUE TITLE
Dossier doesn't build with current bazel 0.4.5

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#102]
Dossier is building with bazel 0.4.0 (on Mac OS X 10.11.6) but with current bazel 0.4.5 I get these errors:

```
[15:02:03 ~/Documents/Programming/js-dossier]$ bazel build :release
...........
INFO: Found 1 target...
ERROR: /Users/erikn/Documents/Programming/js-dossier/src/java/com/github/jsdossier/jscomp/BUILD:1:1: 
Compiling Java headers src/java/com/github/jsdossier/jscomp/libjscomp-hjar.jar (18 files)
failed: Process exited with status 1 [sandboxed].
turbine: invalid flag: -extra_checks:off
Usage: turbine <options> <source files>
use -help for a list of possible options
turbine: no source files
Usage: turbine <options> <source files>
use -help for a list of possible options
Use --strategy=Turbine=standalone to disable sandboxing for the failing actions.
Target //:release failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.223s, Critical Path: 10.61s
```

**Comment by ribrdb** [comment]
If you remove the -extra_checks flag from .bazelrc it gets further, but still fails:
ERROR: /Users/ribrdb/Developer/js-dossier/src/java/com/github/jsdossier/jscomp/BUILD:1:1: Compiling Java headers src/java/com/github/jsdossier/jscomp/libjscomp-hjar.jar (18 files) failed: java failed: error executing command external/local_jdk/bin/java -Xverify:none -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9-dev-r3297-4.jar -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/java/com/github/jsdossier/jscomp/DossierCompiler.java:50: error: cannot find symbol
  private final Es6ModulePassFactory modulePassFactory;
                ^
  symbol:   class Es6ModulePassFactory
  location: class DossierCompiler
src/java/com/github/jsdossier/jscomp/DossierCompiler.java:51: error: cannot find symbol
  private final FileVisibilityPassFactory fileVisibilityPassFactory;
                ^
  symbol:   class FileVisibilityPassFactory
  location: class DossierCompiler
src/java/com/github/jsdossier/jscomp/DossierCompiler.java:62: error: cannot find symbol
      Es6ModulePassFactory modulePassFactory,
      ^
  symbol:   class Es6ModulePassFactory
  location: class DossierCompiler
src/java/com/github/jsdossier/jscomp/DossierCompiler.java:63: error: cannot find symbol
      FileVisibilityPassFactory fileVisibilityPassFactory,
      ^
  symbol:   class FileVisibilityPassFactory
  location: class DossierCompiler
4 errors
Target //:release failed to build

**Comment by adam-rocska** [comment]
@jleyba @ribrdb  : I know this is a dead horse, but it doesn't build on newer ones either.
Here's my version : 

```
INFO: Invocation ID: 5d261cc1-5ba8-4cbf-b365-6e41bee3a820
Build label: 0.21.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:57:09 2018 (1545224229)
Build timestamp: 1545224229
Build timestamp as int: 1545224229
```

and it fails with 

```
INFO: Invocation ID: 7faeb9b4-ffa7-4efd-b47c-70957c51bc28
INFO: Starting clean.
INFO: Invocation ID: 27517545-b9b1-4c4c-ba89-f3d3582463ee
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0,186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @io_bazel_rules_closure; fetching
```
