### ISSUE TITLE
Templates on classes do not consistently show up

### ISSUE THREAD

**Issue by jplaisted** [jleyba/js-dossier#110]
Per https://github.com/google/closure-library/issues/911 from @frenchy64

[goog.html.sanitizer.ElementWeakMap](https://google.github.io/closure-library/api//goog.html.sanitizer.ElementWeakMap.html) does not show the class template type of `T` where as [goog.structs.Set ](https://google.github.io/closure-library/api//goog.structs.Set.html) does. I couldn't figure out the reasoning when I messed around with js-dossier locally. I thought it might be due to the `goog.module` or the fact that `T` is not otherwise used on the constructor, but that wasn't the case. I couldn't get a class template to show up on a simple class I created:

```
goog.provide('my.provide.Provide');

/**
 * The Description
 * @constructor 
 * @template T the template 
 * @param {!T} t the constructor parameter
 */
my.provide.Provide = function(t) {
};

/** @param {!T} t The parameter */
my.provide.Provide.prototype.aMethod = function(t) {};
```

**Comment by jleyba** [comment]
Looks like this issue is obsolete.
