### ISSUE TITLE
Cannot build closure library due to compiler change

### ISSUE THREAD

**Issue by jplaisted** [jleyba/js-dossier#111]
@shicks is reworking how `goog.defines` work. As a result, with the latest library release, dossier can no longer build it because it is using an older version of the compiler that expects `goog.defines` to not be aliased.

```
/home/travis/build/google/closure-library/closure/goog/base.js:250: ERROR - illegal initialization of @define variable goog.TRUSTED_SITE
goog.TRUSTED_SITE = goog.define('goog.TRUSTED_SITE', true);
```

Dossier needs to be updated to use the latest compiler.

===========================

More generally I think the closure compiler team should think about owning dossier. To me, it makes no sense that our dep graph is Compiler <- Dossier <- Library, and we release the Compiler and Library in lock step but expect Dossier not to break. This would help prevent future breakages / reduce time for fixing problems caused by the compiler.

I tried looking into seeing if I could at least build dossier myself, because then presumably all I would need are some permissions to start releasing it. However I'm running in several issues I'll document elsewhere... (#112)

**Comment by myphysicslab** [comment]
I strongly agree about closure team owning dossier.  I suggested this in a [recent thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/closure-compiler-discuss/gIbxSw1-WLo/h2Ghsga5IAAJ) to no avail.

**Comment by jplaisted** [comment]
I guess I should clarify what I mean by ownership. I think Jason should still be the primary owner. But the compiler team should have the permissions needed to keep dossier up to date and unbroken; so they'd be additional owners / maintainers. I don't think the compiler team currently has any throughput for adding features to dossier at the moment.

**Comment by schmidtk** [comment]
@jleyba This issue seems valid, as it prevents generating documentation for projects using recent versions of the Closure Library. Are there plans to update the compiler version to support this?
