### ISSUE TITLE
Cannot build dossier

### ISSUE THREAD

**Issue by jplaisted** [jleyba/js-dossier#112]
Per #111 I'm looking into seeing if I can build dossier, and I can't (linux). Issues thus far:

- The instructions say to install bazel. I installed the latest (0.23) and couldn't build since `http_archive` wasn't defined. This can be solved with an `import()` in the workspace file. But `new_http_archive` isn't defined. So I went back to bazel 0.19 and that resolved this. Either document bazel 0.19 must be used or update the project to work with newer versions.
- The build then failed because a closure bazel rule was checking that bazel was at least version 0.45 (... what?). This was solved by updating `io_bazel_rules_closure` to the latest version in the workspace file (0.8.0).
- `INVALID_SUPPRESS` was removed from the compiler a year ago and needs to be removed from `third_party/BUILD.closure_library`
- I'm currently stuck with the `@AutoFactory` classes not generating anything. I made a new build rule for just `LinkFactory.java` and tried to build it. I can see in the jar that `LinkFactoryBuilder.java` is empty (0 bytes). The error I get when building is:

```
warning: Unclosed files for the types '[com.github.jsdossier.LinkFactoryBuilder]'; these types will not undergo annotation processing
error: Failed to process @AutoFactory annotations:
  java.lang.NoClassDefFoundError: javax/annotation/Generated
  	at com.google.auto.factory.processor.FactoryWriter.writeFactory(FactoryWriter.java:85)
  	at com.google.auto.factory.processor.AutoFactoryProcessor.doProcess(AutoFactoryProcessor.java:187)
       ....
```

I'd make a PR for all of this if I managed to get dossier building completely.

**Comment by jleyba** [comment]
Builds on linux with

```sh
$ bazel version
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```

Will use this to track changes with upgrading to the latest bazel
