### ISSUE TITLE
link aliases are not resolved in goog.scope

### ISSUE THREAD

**Issue by jleyba** [jleyba/js-dossier#13]
goog.provide('foo.bar.baz');
    goog.scope(function() {
      var foo = foo.bar.baz;

      /** @constructor */
      foo.Clazz = function() {};

      /**
       * This link will not resolve: {@link foo.Clazz}.
       * @constructor
       */
      foo.OtherClazz = function() {};
    });

**Comment by jleyba** [comment]
Also impacts `@link` in comments for modules (both commonjs and goog.module)

**Comment by jleyba** [comment]
Current thoughts on resolution order:

- `{@link #name}` should link
  + to instance property of current type (including inherited properties)
  + static property of current type

- `{@link type.name}` should link
  + to a fully-qualified type: `foo.bar.SomeClass`
  + to a fully-qualified static property: `foo.Bar.SomeClass.staticProperty`

`{@link foo.bar}` is _not_ equivalent to `{@link foo#bar}` and should never resolve to an instance property.

When resolving a qualified name:

1. Check the current `goog.scope` block:
    ```
    goog.scope(function() {
    var Foo = foo.bar.baz.Class;

    /** {@link Foo} */
    Foo.someFunc = function() {};
    });
    ```
    Here `{@link Foo}` should resolve to `foo.bar.baz.Class`.

2. Check the current the current file/module:
    ```
goog.module('aModule');

/** 
 * @constructor
 */ 
var Clazz = function() {};
/**
 * See {@link Clazz}
 * @constructor 
 */
var OtherClazz = function() {};

exports.ClassA = Clazz;
exports.ClassB = OtherClazz;
```
    In this example, the `{@link Clazz}` should resolve to `aModule.ClassA`.

3. Check the global scope

**Comment by myphysicslab** [comment]
Some of the above example code might be using `goog.scope` incorrectly: I think the variable name needs to match the package name or class name.  For example, name the variable `baz` instead of `foo` here:

```javascript
goog.provide('foo.bar.baz');
goog.scope(function() {
  var baz = foo.bar.baz;

  /** @constructor */
  baz.Clazz = function() {};

  /**
   * This link will not resolve: {@link baz.Clazz}.
   * @constructor
   */
  baz.OtherClazz = function() {};
});
```
another example, use `Class` instead of `Foo` for the variable name here:

```javascript
goog.scope(function() {
var Class = foo.bar.baz.Class;

/** {@link Class} */
Class.someFunc = function() {};
});
```

**Comment by jleyba** [comment]
The compiler doesn't care what alias you use. I've got alias resolution fixed locally and will push it along with a bunch of other ES6 related changes soon (later this week hopefully)

**Comment by jleyba** [comment]
This is fixed at head. I should have done a better job tracking the commits, but the most important one is 2c83b7e63c25fc1ef153ccd7224c850abef64a6a (see LinkFactoryTest.java). Other interesting commits related to this bug are 1293ec54b73056fcb2fffe84fc19e2696aba2806, a204e0bfc3fa01db3ae453b4516a079eeb447a45, and 2aef66d7b77c74a4f838c6101f35e340e37345ca
