### ISSUE TITLE
JSDoc <code> entity does not honour line end

### ISSUE THREAD

**Issue by lukas-vlcek** [jleyba/js-dossier#24]
It seems to me that \<code/> content in JSDoc does not honour line ends. Example of this can be seen in online documentation for [`goog.format.JsonPrettyPrinter`](http://google.github.io/closure-library/api/class_goog_format_JsonPrettyPrinter.html). Consult generated output with the [source code](
http://google.github.io/closure-library/api/source/closure/goog/format/jsonprettyprinter.js.src.html#l33).

**Comment by jleyba** [comment]
Dossier is doing the right thing here since `<code>` is an inline element (even if the parser didn't collapse the white space, the browser would still would not render line breaks).

The docs for `goog.format.JsonPrettyPrinter` should be updated to use a markdown code block (or `<pre>` tags)
