### ISSUE TITLE
Autofocus the search field in the generated docs

### ISSUE THREAD

**Issue by timothyarmstrong** [jleyba/js-dossier#27]
When the generated docs are opened in the browser (maybe just the `index.html` root doc), it would be great if the search box was autofocused, so that I can immediately start typing for the method or class I'm looking for.

Alternatively, you could make the `/` key focus the search box.

[feature request]

**Comment by jleyba** [comment]
The search box is first in tab order, so you can select it pretty quickly. I like the idea of using `/` to select it though (especially after you've tabbed to another link on the page)

**Comment by timothyarmstrong** [comment]
Awesome!
