### ISSUE TITLE
private classes should still have documentation

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#36]
It is common to provide a group of static functions defined on a particular "utility" class, but the constructor is marked `@private` so that no instance of the class can be made.  Another usage of this is the Singleton pattern, where the constructor is used to make the singleton instance, but the constructor is private to ensure no one else can make an instance.

In the version prior to v0.7.0 this was working perfectly: on a class whose constructor is marked `@private`

+ the class description is shown;  
+ the constructor documentation is absent; 
+ the (public) static functions are shown.
+ the (public) instance methods are shown

In the current version, a class whose constructor is marked `@private` is not documented at all.

For example, here is how such a class was shown in the prior version:

```
class JointUtil
------------------

struct
Provides utility functions for creating Joints.

Static Functions
--------------------

JointUtil.addSingleFixedJoint(sim, body, attach_body, normalType, normal)

Creates a single Joint to attach a RigidBody to a fixed point on the myphysicslab.lab.engine2D.Scrim, at the current world position of the attachment point.

Parameters
sim myphysicslab.lab.engine2D.ContactSim
the ContactSim to which the Joint is added

body myphysicslab.lab.engine2D.RigidBody
the RigidBody to add joints to

...rest omitted...
```

Here is the definition of that class

```javascript
/** Provides utility functions for creating {@link myphysicslab.lab.engine2D.Joint
Joints}.

@constructor
@struct
@private
*/
myphysicslab.lab.engine2D.JointUtil = function() {
  throw new Error();
};
```

If I remove the `@private` directive from the constructor, the class is documented as before, without the constructor (but with class description and static functions), even though the constructor is presumably public. But this is related to issue #37

**Comment by jleyba** [comment]
This is due to changes related to #26

**Comment by myphysicslab** [comment]
For me this is all working fine and this "bug" could be closed.  I believe that this commit fixed it:
e5e70f46917ba2777848d1e9bb7840145f456b7d
