### ISSUE TITLE
fail to make link to a method in the class

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#38]
Using the syntax `{@link #methodBar}` fails to make a link, instead of an `<a>` tag the resulting html has `<code>#methodBar</code>`.  New problem in v0.7.0.

This happens in method descriptions.  In the class description (the comment on the constructor) these types of links are still working.

**Comment by jleyba** [comment]
Bug is confirmed.  The TypeInspector, introduced in commit 7c280edc1e30edb779c8a3475640bd783027abd5, is not tracking the context in which comments are parsed, so `{@link}s` never resolve.

**Comment by myphysicslab** [comment]
Confirmed fixed in commit 61b5b0132a8aba93ab1b10473a889149ec00fdcf
