### ISSUE TITLE
how to have comments in a code sample?

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#46]
I want to show a code sample that includes comments, but the closing comment is being interpreted as the actual closing comment.  You can see the same thing happening here with the github markdown:

 ```javascript
/** Provides access to a string value of a Subject.

(... docs omitted...)

This is why when setting up a ParameterString (or ParameterNumber) that represents an
enum we must use a special setter function that takes the input string and converts that
to an enum before calling the subject's setter method. Here is an example from
ContactSim's constructor:

   this.addParameter(new ParameterString(this, RigidBodySim.strings.EXTRA_ACCEL,
      this.getExtraAccel,
      (/** function(this:myphysicslab.lab.engine2D.ContactSim, string) */}
      (function(s) { this.setExtraAccel(ExtraAccel.stringToEnum(s)); })),
      ExtraAccel.getChoices(), ExtraAccel.getValues()));

That code uses a closure compiler "type cast": the type is in a comment followed
by the object in parenthesis. (The comment symbols have an extra space because of
limitations of the document generation).

@param {!myphysicslab.lab.util.Subject} subject the Subject whose value this
    ParameterString represents
@param {string} name the localized name of this Parameter
@param {function(this: myphysicslab.lab.util.Subject): string} getter A method of
    `subject` with no arguments that returns the value of this Parameter
@param {function(this: myphysicslab.lab.util.Subject, string)} setter A method of
    `subject` with one argument that sets the value of this Parameter
@param {!Array.<string>=} opt_choices the translated localized strings corresponding to
    the values (optional)
@param {!Array.<string>=} opt_values the language-independent strings that the parameter
    can be set to (optional)
@constructor
@struct
@implements {myphysicslab.lab.util.Parameter<string>}
@implements {myphysicslab.lab.util.SubjectEvent}
*/
myphysicslab.lab.util.ParameterString = function(subject, name, getter, setter,
    opt_choices, opt_values) {

```

I tried using the html entity `&#047;` but that shows up as `&#047;` instead of a slash.  If there was a markdown escape character for slash that might work, but there is only markdown escape for backslash.

The problem seems to be that when something is in a code section, then you cannot use html entities.  For example:

```javascript
This is a github code section and &#047; does not appear as a slash
```

I guess this is a conflict between the JavaScript environment which will see `*/` as the end of a comment and the markdown code section where the only way to write that is as `*/`.

A workaround is to just put a space:  `* /` which is probably good enough for the docs.

**Comment by jleyba** [comment]
This is an interesting problem. I was able to get it to work with a zero-width space (U+008B). The trick is _how_ to get that that character into your comment.  What I did was opened the Chrome console and executed:

```
console.log('*\u008b/');
```

I then copy+pasted the output into my comment and dossier rendered everything correctly. Unfortunately I couldn't get it to work by typing 008b into my text editor (it intelligently strips out the zero-width space).

**Comment by myphysicslab** [comment]
Cute hack!  That works good enough for me.

Note that having this strange character in a source file is a bit fragile: easy for someone in the future to remove the zero-width space because they don't understand what it is or why it is there.

**Comment by myphysicslab** [comment]
After thinking this over, I'm backing away from putting non-ASCII characters like (U+008B) in my source code.  I suspect that these will cause trouble in future with other developers environments.  So I'm going back to putting a regular space in like `* /`.
