### ISSUE TITLE
Documenting ES6 Code

### ISSUE THREAD

**Issue by ryanvanoss** [jleyba/js-dossier#47]
Any plans to support ES6 in the near future? Or, is there a way to compile down to ES5 and generate the docs from the compiled code?

**Comment by jleyba** [comment]
If you specify ES6 as your input language, it will be compiled to ES5_STRICT for analysis

**Comment by ryanvanoss** [comment]
Awesome. Battling some proxy hoopla right now, but once I get that fixed I'll pull & build and give it a shot.

**Comment by ryanvanoss** [comment]
Thanks!

**Comment by ryanvanoss** [comment]
It looks like anytime you import or export a module, it outputs the compiler's internal namespacing (e.g. `Bar$$module$...$Bar`. Is this by design?

I setup a quick repo so you can see this in action:

```bash
git clone https://github.com/ryanvanoss/js-dossier-es6-test`
npm run docs
```


![screen shot 2015-10-26 at 3 43 52 pm](https://cloud.githubusercontent.com/assets/137956/10744654/ca93eef2-7bf8-11e5-976b-718add70f475.png)

**Comment by jleyba** [comment]
I'll have to see if I can add a pass to look for ES6 modules before the compiler starts rewriting stuff. Worst case, you'll have to specify module inputs as `modules` instead of `sources` in your config file (right now `modules` only looks for commonjs modules).

**Comment by ryanvanoss** [comment]
I don't have a strong preference either way; specifying them as modules would be fine.

**Comment by jleyba** [comment]
This only required a few changes, but I ended up doing a bunch of cleanup work. Long story short, this is almost done. Dossier will automatically detect ES6 modules from the presence of an export expression. You still have to declare Node-style modules so it'll know to look for `exports.x` and `require` statements.

I've also added alias tracking on imports, so if you have

    import {One, X as Y} from './foo';
    import * as util from './foo/bar/utils';

you'll be able to refer to `One`, `Y`, and `util` as linkable symbols (e.g. `{@link One}`) in JSDoc comments.

**Comment by ryanvanoss** [comment]
Good stuff. I'll pull it down and give it a go on a few components and let you know if I hit any snags.

Thanks!!

**Comment by jleyba** [comment]
Just to clarify: I haven't pushed any of the changes yet.

**Comment by ryanvanoss** [comment]
Yeah, I saw that right after I commented. Regardless, looking forward to it.

**Comment by ryanvanoss** [comment]
Hey @jleyba,

First of all, thanks for the updates! Great to see the ES6 support coming along.

This does output module documentation for ES6-style modules, however it casts them to module style documentation, and doesn't appear to support classes, even with `@class` annotations. It will also throw on ES6 code that does not export. The latter being a rare case, and probably not too useful as it would mean a class whose scope would be limited to code within its own source file. The former is what I'm more concerned with -- I lose method documentation when the ES6 class is defined as a module.

I updated my [test repo](https://github.com/ryanvanoss/js-dossier-es6-test.git) with the latest jar. You can run `npm run docs` to see it throw, and `npm run docs-modules` to see the output documentation sans method docs.

Let me know what you're thinking and/or if this is something that you'll consider adding.

Cheers,
Ryan

**Comment by jleyba** [comment]
Tracking the incorrect handling of default exports in #51.

**Comment by jleyba** [comment]
Take 2!

In your test repo, Baz.js will be documented as an empty module because it has an import declaration, but no exports. If you add a `@fileoverview` jsdoc comment to Baz.js, that will be included in the documentation.

There are a few issues remaining, but I don't consider them as blocking this issue:

1. The generated docs for default exports feels awkward. Not sure how these can improved yet.
2. Documentation on classes is still sparse b/c of #49.
