### ISSUE TITLE
Publish as NPM module

### ISSUE THREAD

**Issue by isabo** [jleyba/js-dossier#52]
How about publishing as an NPM module? This will make it easier for projects that manage their dependencies using NPM to get the latest version of Dossier in an automated way.

The issue is that you don't include your binary (dossier.jar) as part of your repo -- instead it's a download attached to a release. 

Alternatively, I'd be happy to package your binary, license and readme an publish to npmjs.com, in a similar manner to how the [google-closure-compiler](https://www.npmjs.com/package/google-closure-compiler) offers the binary from [google/closure-compiler](https://github.com/google/closure-compiler). I've prepared a repo [isabo/js-dossier-npm](https://github.com/isabo/js-dossier-npm), but haven't published to NPM yet -- in case you want to do it as part of your repo.

Let me know what you think. BTW thanks for a great tool!

**Comment by jleyba** [comment]
Sure, I can publish the next release to npm (by EOY)

**Comment by isabo** [comment]
Great!

**Comment by jleyba** [comment]
The 0.8.0 has been published to [npm](https://www.npmjs.com/package/js-dossier)
