### ISSUE TITLE
Exported types not properly tracked with module.exports shorthand

### ISSUE THREAD

**Issue by jleyba** [jleyba/js-dossier#54]
```
/** Class Foo. */ class Foo {}
/** Class Bar. */ class Bar {}

// A
module.exports = {Foo, Bar}

// B
exports.Foo = Foo;
exports.Bar = Bar;
```

With style `(A)`, Dossier will capture the exported types, but the constructor docs will be lost.

**Comment by schmidtk** [comment]
@jleyba It appears this is still an issue. Are there plans to support documenting exports that use destructuring assignment? I'm specifically encountering this with `goog.module` while transitioning code to ES6. Style A does not work with `js-dossier`, while style B does work.
