### ISSUE TITLE
Feature request: Support custom "view source" links

### ISSUE THREAD

**Issue by joeltine** [jleyba/js-dossier#55]
We'd like to be able to link to the GitHub version of our source code in the API docs under "View Source". It'd be awesome if this was configurable somehow. This would also obviate the need to copy the entire source tree along with the API documentation. Presumably, this would speed things up.

Does this seem feasible?

**Comment by joeltine** [comment]
@shicks

**Comment by jleyba** [comment]
Sounds reasonable. Copying the files only takes a few seconds, but this
would cut down on the size of the generated docs.

How should it handle version skew? Just link to the file at head and hope
the line number is accurate, or require a specific version?

**Comment by joeltine** [comment]
My first thought is to make pushing the external API a part of the source code release process. This will ensure they're always in sync and we can just point to head.

**Comment by joeltine** [comment]
I should say *almost* always in sync. Pull requests could cause issues for a small window of time. The alternative is to regenerate the API as a part of every commit on Travis. I'll think about it.

**Comment by jleyba** [comment]
I think this can be solved with a new config option: `remoteSourcePath`. If set, this must be a http(s) URL that will be used as the prefix for source links.

For Closure, `remoteSourcePath` would be https://github.com/google/closure-library/blob/master

**Comment by shicks** [comment]
I'm not sure that would quite work - jsdossier's generated files get .src.html added to them, and the way to specify the line number is (slightly) different. Seems like we need a pattern rather than just a prefix.

**Comment by jleyba** [comment]
How about taking a template string and dossier replaces `{$path}` and `{$line}`:

`https://github.com/google/closure-library/blob/master/{$path}#L{$line}`

**Comment by shicks** [comment]
That should work great.
