### ISSUE TITLE
Include type reference information

### ISSUE THREAD

**Issue by jleyba** [jleyba/js-dossier#57]
- [X] Class type hierarchy
- [X] Implemented/extended interfaces
- [ ] All known implementations (interfaces only)
- [ ] All known sub-types (classes only)
- [ ] All known type aliases

**Comment by myphysicslab** [comment]
Upvote.  In my project I've been adding these "all known" lists manually.  They tend to get out of date.  They would be more likely to be correct if it's automatically generated.
