### ISSUE TITLE
Dossier build system integration

### ISSUE THREAD

**Issue by jart** [jleyba/js-dossier#62]
I'm working on a new Closure Tools build system for Bazel. Dossier is the official Closure documentation generator. So I'd like to integrate it as the recommended doc tool. However I have two concerns.

Ideally, I would like to be able to download Dossier from Maven as a single jar that includes its dependencies. This is because each external dependency I add to the Closure Rules incurs a social cost. Bazel forces the developer to not only maintain his own dependencies, but also the transitive dependencies of everything he uses. If integrating with Dossier carries the cost of twelve additional dependencies, then developers may be less inclined to use the Closure Rules.

I would also like to be able to configure Dossier with flags rather than JSON. Bazel build rules aren't really able to automate writing JSON.

Are these changes you would consider @jleyba?

**Comment by jleyba** [comment]
I can look into publishing releases to maven.

Does Bazel know how to use npm for external deps? Dossier is already published there:
https://www.npmjs.com/package/js-dossier

I filed #63 for using flags instead of JSON

**Comment by Dominator008** [comment]
@jleyba Bazel works with Maven but not NPM yet, I think.

**Comment by jleyba** [comment]
Is it possible to configure maven to publish a prebuilt jar? I don't want to maintain two build systems.

**Comment by Dominator008** [comment]
@jleyba See https://maven.apache.org/plugins/maven-deploy-plugin/usage.html. I think you want to use the deploy-file Mojo.

**Comment by jleyba** [comment]
Tracking publishing to maven in #68
