### ISSUE TITLE
<ol> tag being removed by HtmlSanitizer

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#75]
When a comment has markdown that results in an &lt;ol&gt; tag with a starting point other than the default, this is removed by HtmlSanitizer.

The markdown is a list where items start with a number.  If the first number is for example zero, then you wind up with html like:

    <ol start="0">

The error message is:

    [WARNING][com.github.jsdossier.soy.HtmlSanitizer] 
    In tag "ol", removed attributes: ["start"], from text:

**Comment by jleyba** [comment]
What version are you using? This was fixed in 5aaffa1f2ed5029f01498c8757c55863a951a4bf (included in the 0.10.0 release).

**Comment by myphysicslab** [comment]
You are correct, it is fixed.  I got confused on what version I was testing when updating today.
