### ISSUE TITLE
index.html generated from README.md is not a valid HTML file

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#79]
The index.html file generated from README.md is not a valid HTML file: it does not have tags such as `<html>`, `<head>`, `<body>` or their closing tags.  Tags that should be in the `<head>` section such as `<meta>` and `<title>` are mixed with `<body>` section tags like `<h1>` and `<p>`.

See for example the `index.html` file at:
http://google.github.io/closure-library/api/index.html

From the Dossier instructions:

> `readme` Path to a README file to include as the main landing page for the generated documentation. This file should use markdown syntax.

**Comment by jleyba** [comment]
`<html>`, `<head>`, and `<body>` are all optional with `<!DOCTYPE html>`:

https://www.w3.org/TR/html5/syntax.html#syntax-tag-omission

There are, however, a handful of minor validation errors I need to fix:

https://html5.validator.nu/?doc=http%3A%2F%2Fgoogle.github.io%2Fclosure-library%2Fapi%2Findex.html

**Comment by myphysicslab** [comment]
Today I learned that most HTML tags are optional !
