### ISSUE TITLE
building a release should not run tests

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#97]
When doing

    ./gendossier.sh -r

it runs all the tests and then builds the release.  That's OK for the default behavior with no flags specified, but when I specify `-r` it should just build the release.

**Comment by jleyba** [comment]
You can just run `bazel build :release` from the depot root to build the release artifacts -- or if you just want the jar, `bazel build //src/java/com/github/jsdossier:dossier_deploy.jar`

The gendossier.sh script handles all of the steps, including running the tests to ensure the build is valid)
